# Welcome to Codecypher!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Codecypher
email: chirag.visavadia@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my blog 'Codecypher', this blog  contains detailed information and tutorials regarding technologies and framework like JDK8, Spring, BigData, Apache Hadoop, Apache Spark, NoSql and many others.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: chiragvisavadia
github_username:  cypherkaka

# Build settings
markdown: kramdown

theme: jekyll-theme-cayman