# Welcome to Codecypher!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cypherkaka
email: chirag.visavadia@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my blog 'Cypherkaka', this blog contains information and tutorials regarding technologies and frameworks like BigData, Apache Hadoop, Apache Spark, Apache Kafka, NoSQL, JDK8/9, Spring, Hibernate and many other open source frameworks.

  Basically, I have created this blog to explore opensource frameworks and remember all technical details that I have worked on or going to work with as my learning curve.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cypherkaka.github.io/" # the base hostname & protocol for your site
twitter_username: chiragvisavadia
github_username:  cypherkaka

# Build settings
markdown: kramdown

theme: jekyll-theme-minimal
